language: python


python:
  - "2.7"
  - "3.6"

env:
  - DB=mysql
  - DB=sqlite

services:
  - docker

before_install:
  - if [ $DB = "mysql" ]; then
       docker pull mysql:8.0;
       docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql;
       docker ps -a;
       docker exec mysql mysql -ppassword --execute="CREATE DATABASE test";
       pip install pymysql;
    fi

install:
  - python --version
  - pip install sqlalchemy
  - python setup.py install

script:
  - if [ $DB = "mysql" ]; then export GRAFF_TEST_DATABASE_URI=mysql+pymysql://root:password@localhost/test; fi
  - cd tests
  - nosetests
