language: python


python:
  - "2.7"
  - "3.6"

env:
  - DB=mysql
  - DB=sqlite

services:
  - docker

before_install:
  - test $DB = "mysql" \
   && docker pull mysql:8.0 \
   && docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql \
   && docker ps -a \
   && docker exec mysql mysql -ppassword --execute="CREATE DATABASE test"
   && pip install pymysql

install:
  - python --version
  - pip install sqlalchemy
  - python setup.py install

script:
  - test $DB = "mysql" && export GRAFF_TEST_DATABASE_URI=mysql+pymysql://root:password@localhost/test
  - cd tests
  - nosetests
